### ISSUE TITLE
can not install FFTrees from CRAN

### ISSUE THREAD

**Issue by jyk** [ndphillips/FFTrees#1]
Hi!
I am using R version 3.3.0.
I can not install FFTrees from CRAN:
> install.packages("FFTrees")
Installing package into ‘C:/Users/jyriku/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘FFTrees’ is not available (for R version 3.3.0)

**Comment by ndphillips** [comment]
Strange, it works fine on my end and appears to be up just fine on CRAN (https://cran.rstudio.com/web/packages/FFTrees/index.html)

Can you try installing from a different CRAN mirror? Also on another computer? See if you get the same error

**Comment by jyk** [comment]
I got the same error when I changed the mirror.

**Comment by jyk** [comment]
My initial mirror was: "Global (CDN) - RStudio"

**Comment by jyk** [comment]
However, I installed the package from source, so I have it now

**Comment by ndphillips** [comment]
Hmmm, unfortunately I'm not sure how to help on this one. FFTrees is definitely available on CRAN for R > 2.1.0...

**Comment by ndphillips** [comment]
Ok glad you were at least able to install it. If the error occurs on another machine, let me know.

**Comment by ndphillips** [comment]
I'll close the issue for now...hopefully it will just magically resolve itself with time :) if not bug me again!
