### ISSUE TITLE
Incorrect showcues() graph after plot() in RStudio

### ISSUE THREAD

**Issue by Spinwing** [ndphillips/FFTrees#11]
Hello

RStudio 0.99.902, R 3.3.1
```
> mushrooms.fft <- FFTrees(formula = poisonous ~.,
+                      data = mushrooms,
+                      train.p = .5)
> showcues(mushrooms.fft)
> plot(mushrooms.fft)
> showcues(mushrooms.fft)

```
![rstudio_bug](https://cloud.githubusercontent.com/assets/19976875/18007379/237e8b08-6ba4-11e6-9888-cf187e6d66cb.png)

If I execute a plot(FFTree) and then a showcues(), the graph is drawn in the upper part of the device.

Does not happen in RGui.

Thanks
Stefano

**Comment by ndphillips** [comment]
@Spinwing  This is because the plotting layout was changed when you ran plot.FFTrees().  Clear your plotting space with `dev.off()` then try again

**Comment by Spinwing** [comment]
That's ok, I came to the same conclusion, however I think (maybe I'm wrong) that the package should do it as a default.

**Comment by ndphillips** [comment]
Good point. I just added and pushed the update. Should be working now in GitHub version 1.1.5
