### ISSUE TITLE
Space in tree definitions

### ISSUE THREAD

**Issue by Eva-biostat** [ndphillips/FFTrees#111]
In the tree definitions, if there is a space before a cue like this:
cues = c("sbp_min;nlacven; si_min")
the cue will not be evaluated. 
The FFT will appear but there will be nothing at that node and the observations will be excluded.
The correct way is this:
cues = c("sbp_min;nlacven;si_min")
Maybe there should be a warning about this. The thresholds have spaces, and it is not a problem.
Best wishes,
Eva

**Comment by pa-nathaniel** [comment]
@hneth I met with @Eva-biostat today and we discovered this issue.

My proposal to fix this issue would be to 

* Throw a warning if there are any leading or trailing spaces in cue names
* Remove those spaces (i.e.; with `stringr::str_trim()`

**Comment by hneth** [comment]
Hiyall ~~

yes, that's definitely something that needs fixing. I can only guess that this hasn't come up before as only a few people are manually editing tree definitions.

Will investigate and report back asap...

Best,
Hans

**Comment by hneth** [comment]
Hi Eva,

thanks for pointing out this issue!

I was unable to reproduce the exact error, but mostly because I did not know which function(s) you're using to read in the tree definitions with leading spaces in the corresponding list of cues.  Perhaps you could post or send me the expression that does this?

In an updated version of the package (v1.7.5.9007), I removed both leading and trailing spaces when interpreting cue definitions (when internally calling the `fftrees_apply()` function).  This may solve the problem — so I'd be grateful if you could check whether this works for you.

Best,
Hans

**Comment by Eva-biostat** [comment]
Yes, the version of my FFT package is much older (v1.3.5). That could be the reason. And where may I find the most recent version?

**Comment by hneth** [comment]
That's really quite an old version — and might explain why I was unable to reproduce the error.

You can find the latest version of **FFTrees** [here on GitHub](https://github.com/ndphillips/FFTrees) and install it via the **devtools** package, as in:

```
# install.packages("devtools")
devtools::install_github("ndphillips/FFTrees", build_vignettes = TRUE)
```

That said, I'm still curious which function you've been using to enter the list of cues, as the current version does not even seem to have such an argument. And checking the compatibility of a user-defined FFT with a set of data would be a useful feature in any case.

**Comment by Eva-biostat** [comment]
Thank you, Hans! The function is data.frame. It has the following arguments: tree, nodes, classes, cues, directions, thresholds, exits. Using this function, I create my.tree.definitions object. Then I pass this object as tree.definitions argument to the FFTrees function.

**Comment by hneth** [comment]
That's interesting indeed — **thanks** for your answer, Eva!

It appears that the `tree.definitions` argument of the `FFTrees()` function is no longer supported by the current version of **FFTrees**.  It's still present, of course, but simply not being used anywhere in the code. 

However, as manually defining a set of FFTs (as a data frame in the required format) makes perfect sense, I'll try to find out how we can recover this functionality.  Essentially, replacing the tree definitions of an `FFTrees` object `x` by `tree.definitions` and then re-applying those trees to the current data with the `fftrees_apply()` function should do the trick.  But I need to investigate further to make sure that this does not lead to undesired side-effects somewhere else.

I'll report back when I know more...

Best,
Hans

**Comment by hneth** [comment]
Dear Eva,

the latest development version (v1.7.5.9009) aims to re-enable the use of `tree.definitions` (as a data.frame) for an existing `FFTrees` object when using the `FFTrees()` function.  

At this point, the format and contents of the data frame provided as `tree.definitions` and its fit to the current data are not being verified at great length. However, I've run some quick tests that seemed to work for reasonable definitions and they now also succeeded when those definitions included leading or trailing spaces.

Perhaps you could kindly check whether this updated version works for your code and purposes as well?

Best,
Hans

**Comment by hneth** [comment]
**PS:** The updated development version (v1.7.5.9010) allows providing FFTs either as a `data.frame` of `tree.definitions` or as part of an existing `object`. If both arguments are provided, `tree.definitions` take priority.  In addition, user feedback on current status and progress is improved.  

I'm still testing those changes and plan to revise the vignette on **Manually specifying FFTs** accordingly.

**Comment by Eva-biostat** [comment]
Hi Hans,
Thank you, I will probably play with after the paper takes flight. I am happy that everything works at this point and that things are improving for the future.
Best wishes,
Eva

**Comment by hneth** [comment]
Hi Eva & @pa-nathaniel, 

the latest PR #118 added a check that all cues occurring in FFT definitions are present in the current `data` (when applying definitions).  

I'm yet to revise the vignette that illustrates and explains the new features, but think that the current changes will warrant a release of **FFTrees** v1.8.0 soon (aiming for early January).

Best,
Hans

**Comment by hneth** [comment]
**FFTrees** version 1.8.0 was released [on CRAN](https://cran.r-project.org/package=FFTrees) today [2023-01-06] 
(see <https://github.com/ndphillips/FFTrees/releases/tag/v1.8.0> for details).

This addresses the problems with manual tree construction (i.e., using spaces between cues and the `tree.definitions` argument). Thanks for pointing out these issues! 

Best,
Hans
