### ISSUE TITLE
Re-using cues to capture non-linear relationships

### ISSUE THREAD

**Issue by hneth** [ndphillips/FFTrees#12]
Consider using a cue multiple times to capture _non-linear relationships_ between cue and criterion.  

For instance, if both children and older adults of the Titanic survived, it would be good to use split a cue into 3 categories:
- age <= 18:  survived
- 18 < age < 60:  dead 
- age >= 60: survived 

The ability to re-use a cue + using the conditional cue validity (i.e., only calculates current cue validity for those cases which have not been classified yet) should already accomplish this.

**Comment by ndphillips** [comment]
Done!
