### ISSUE TITLE
Unexpected error when running FFTrees() on training data with a single feature

### ISSUE THREAD

**Issue by pa-nathaniel** [ndphillips/FFTrees#170]
Trying to run `FFTrees()` on training data with a single feature appears to lead to an ungraceful error:

Here's a reprex:

```
library(FFTrees) # v 1.9.0.9013

data_train <- data.frame(x = c(1, 2, 3, 4, 5),
                                           crit = c(TRUE, TRUE, FALSE, TRUE, FALSE))

x <- FFTrees(crit ~ .,
             data = data_train)
```

Returns

```
✔ Created an FFTrees object.
Error in `dplyr::pull()`:
! Problem while evaluating `x$criterion_name`.
Caused by error in `x$criterion_name`:
! $ operator is invalid for atomic vectors
```

I believe the error is triggered here: https://github.com/ndphillips/FFTrees/blob/5b556d1f8fe6197ca17671fb2fe9bac0f2b1b0af/R/fftrees_cuerank.R#L60

I'm about to create a PR with a fix that solved it for me

I'm using FFTrees 1.9.0.9013 and dplyr 1.1.0

**Comment by hneth** [comment]
Thanks for spotting this issue — and for immediately solving it!

When working on current issues (e.g., including `NA` values and accounting for costs), it's really important and helpful to include simple plausibility checks like this. 

I've run a few modified tests and encountered no new problems (but occasional messages of vectors with "no variance" or cues that are "nominal and contains mostly unique values").  Hence, should we close this particular issue?
