### ISSUE TITLE
Warning! Your DV is not binary. Convert to binary (0, 1)

### ISSUE THREAD

**Issue by ncdingari** [ndphillips/FFTrees#2]
First of all, Thank you for the package for FFTrees. I am getting the error below. However, my target variable is numeric and binary. I also changed it to factor tried, but did not work. When I used less number of predictors, it is working fine.

```
Error in fft(formula = myFormula data = myData) : 
  Warning! Your DV is not binary. Convert to binary (0, 1)
```

**Comment by ndphillips** [comment]
@ncdingari Can you show me the structure of your data?

`str(myData)`

**Comment by ncdingari** [comment]
I have a very large data set with all 'numeric' and 'factor' variables

**Comment by ndphillips** [comment]
I see. But it would still help if you could show me the output of `str(myData)` as well as the code you used to generate the tree.

**Comment by ncdingari** [comment]
I am not plotting the tree yet, just using `fft` function
It seems the error is coming from the below code in your `fft` function

```
## VALIDITY CHECKS
{
# Non-binary DV
if(setequal(unique(data[,1]), c(0, 1)) == F) {

  stop("Warning! Your DV is not binary. Convert to binary (0, 1)")

}

}
```

**Comment by PTschandl** [comment]
It seems the fft() function does not understand factor variables with two levels (which would be useful), only a variable coded with 0 and 1.

**Comment by ndphillips** [comment]
@PTschandl yes the DV must be either logical or contain only 0s and 1s.
@ncdingari Have you tried converting your DV to a logical variable? If you do it should work. Again, if you show me `str(myData)` that would help :)

**Comment by ndphillips** [comment]
I think this has been resolved...if not please reopen!
