### ISSUE TITLE
Do we want to have a data_old folder?

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/FFTrees#211]
@hneth and @jelenameyer  I noticed that we have a `data_old` folder in the root level of the package (https://github.com/ndphillips/FFTrees/tree/master/data_old). 

I suspect that this isn't part of the standard R package structure and wouldn't be included in releases. 

Can someone help me understand what the purpose of this folder is? Is it used in the package?

**Comment by hneth** [comment]
This folder can simply be deleted (as the `data` folder contains all necessary files) (see PR #212).
