### ISSUE TITLE
FFTrees for non binary problems

### ISSUE THREAD

**Issue by instantkaffee** [ndphillips/FFTrees#22]
This is more a question rather than an issue:
Is it possible to use FFTrees also for building a decision tree for more than 2 ourcomes i.e. 3 up to 5 categories.

**Comment by ndphillips** [comment]
Hi @instantkaffee, currently there is no option to do this in `FFTrees`. It's definitely possible in theory, but as it would require a pretty substantial change to the tree construction algorithm, it's unlikely I would try to implement this personally in the near future. For now, I'd recommend using standard decision trees (e.g.; `rpart()`)  :)
