### ISSUE TITLE
R-CMD check failing on master?

### ISSUE THREAD

**Issue by pa-nathaniel** [ndphillips/FFTrees#220]
I just saw that the R-CMD check is failing on master, seemingly after the latest merged PR from @hneth. See https://github.com/ndphillips/FFTrees/actions/runs/9187821475

Seems to be related to an error on ubuntu regarding installing the `pak` package https://github.com/ndphillips/FFTrees/actions/runs/9187821475/job/25266309204. Though I'm not sure why that would be needed as part of the package.

@hneth any thoughts here?

**Comment by hneth** [comment]
Thanks for the note!  I also noticed the failed check, but as all my downstream checks were successful it seems that this was merely a glitch in one particular testing pipeline.  Seems to work again now, so will close this issue.
