### ISSUE TITLE
heuristic_algoritme formula in cuerank

### ISSUE THREAD

**Issue by descheppermieke** [ndphillips/FFTrees#23]
In file: FFTrees/R/heuristic_algorithm.R line 84 the formula is not always working. When there are factors you get an error, as the names of the data.frame has changed.

I think the solution is something like this: 
formula(paste0(colnames(data.mm)[1], "~" , paste(colnames(data.mm)[-1], collapse=" + ")))

**Comment by ndphillips** [comment]
hmmm, it should work with factors. For example, this works:

```
# ChickWeight data (contains factors)
data <- ChickWeight

# Add random criterion
data$criterion <- sample(c(0, 1), size = nrow(data), replace = TRUE)

# Create FFTrees
data.fft <- FFTrees::FFTrees(criterion ~., data = data)
```

can you give me a reproducible example where it crashes?

**Comment by ndphillips** [comment]
Has been fixed over email :)
