### ISSUE TITLE
cost.outcomes and cost.cues good features  gone? 

### ISSUE THREAD

**Issue by jacekkotowski** [ndphillips/FFTrees#27]
Sorry, they are in a github newest version. I loaded the cran version. Please delete this issue

**Comment by ndphillips** [comment]
They are also in CRAN (I think). But to get the algorithm to use them in building trees, you need to specify the goal and goal.chase arguments:

```
x <- FFTrees(formula = diagnosis ~.,
data = heartdisease,
cost = c(0, 10, 100, 0),
goal = 'cost',       # Minimize cost in selecting a tree
goal.chase = 'cost') # minimize cost in growing trees
```
