### ISSUE TITLE
more a tutorial than a code question

### ISSUE THREAD

**Issue by timm** [ndphillips/FFTrees#29]
i'm trying to understand:
when generating the ROC trees, what is being varied internally to the FFT trees?

**Comment by ndphillips** [comment]
Hi Tim. The ROCs are generated by different exit structures. That is, the algorithm creates several different trees with different patterns of left (i.e. False) and right (True) exits. Trees with mostly left exits tend to have low sensitivities and high specificities, while the opposite is true for trees with mostly right exits. You can read more about the tree building algorithms here: http://journal.sjdm.org/17/17217/jdm17217.pdf Hope that helps!

**Comment by timm** [comment]
did you ever see my "data mining for very busy people" stuff? same song as FFT, i think.

- 2003: http://www.utdallas.edu/~xxg061000/utdcs-rank.pdf

more generally, there is much evidence that some domains are inherently low dimensional so thing more complex than fft will rarely be required

- 2007: http://menzies.us/pdf/07strange.pdf
- 2017: http://tiny.cc/tim17vic

recently we have much success with the low dimensionality assumption, applied to very complex multi-objective optimization. in the following, just a few (very small) decision trees applied (one per objective) did far better than much more complex algorithms

- https://arxiv.org/pdf/1705.05018.pdf

just fyi

**Comment by ndphillips** [comment]
Thanks very much for the links!! I had not seen your work and indeed it looks extremely relevant and insightful. I come from a psychology background where it took us until the 2000s -- most notably with Gigerenzer and colleagues (https://www.amazon.com/Simple-Heuristics-That-Make-Smart/dp/0195143817) and (http://onlinelibrary.wiley.com/doi/10.1111/j.1756-8765.2008.01006.x/full)-- to fully appreciate the rational benefits of simplicity. I'm always excited to see similar insights from a purely computer science background.

Thanks again for sharing, I look forward to reading them and will get back to you if I have any questions!
