### ISSUE TITLE
Removal cues with no variance

### ISSUE THREAD

**Issue by smbache** [ndphillips/FFTrees#3]
You might want to change

```R
length(unique(data[, x]))
```

to 

```R
length(unique(data[[x]]))
```
in 

https://github.com/ndphillips/FFTrees/blob/master/R/predictfft_function.R#L219

The current line does not give you the count of uniques if the input is a `tibble` (used by `dplyr` and friends).

**Comment by ndphillips** [comment]
Cool beans. I'll update this in the next version!

**Comment by ndphillips** [comment]
In the pipeline.
