### ISSUE TITLE
multi-class trees

### ISSUE THREAD

**Issue by synikitin** [ndphillips/FFTrees#30]
Hello,

Can the algorithms be adapted for multi-class use?

Slava

**Comment by ndphillips** [comment]
Unfortunately this is not possible for the algorithms currently in `FFTrees`. However, I do know of another fast-and-frugal tree package called `fftr` soon to be released on CRAN which contains algorithms that do allow for multiple classes. Once it's released I'll include it as a required package in `FFTrees` and then allow the user to select its algorithm(s)
