### ISSUE TITLE
> 2 classes algorithm

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/FFTrees#33]
Goal: Create an FFTrees building algorithm that allows for classifying more than 2 classes.

*Method A*

The basic idea is to, for each cue / class combination, calculate a decision threshold that maximises a *joint* function of classification accuracy and percentage of cases classified. For example, a threshold that classifies 80% of class A with an accuracy of 90%, might be preferred to a threshold that classifies 70% of class A with an accuracy of 95%. 

For example, in the plot below, I show the relationship between classification proportions, and classification accuracy, for many different thresholds. The best value should be one that has a relatively high classification proportion, and accuracy.

In this case, threshold #33 might a good choice, because it has a relatively high accuracy around 90%, where 10% of cases are classified.

![image](https://user-images.githubusercontent.com/8480980/33139101-9a40f3bc-cfac-11e7-934c-f6f9ae3fabe2.png)

**Comment by hneth** [comment]
A very interesting and important goal indeed!  Just a quick note on our discussion:

As I find it tricky to evaluate the consequences of a 3x3 contingency table, I'd first suggest trying to use the existing algorithm to classify any category A versus all _others_ (e.g., categories B and C) at every level of a tree. This would still result in a FFT structure (with one exit at every node), be a straightforward extension of the current algorithms, and should scale linearly with the number of categories.  

It may be necessary to include some requirement to use every category at some point (e.g., on the last node), but it may also be informative if a category that is being considered never gets selected as a best possible exit. Actually, this would allow for an algorithm that starts out with _N_ candidate categories, but yields FFTs with fewer ones — another way of being frugal. 

Furthermore, it seems plausible that — as the number of categories increases — the conditional algorithm may be more successful than the unconditional one.  But as this would mainly yield benefits in fitting, it remains an empirical question to what extent such FFTs constructed by different algorithms would succeed or suffer in prediction.  

Regardless of which algorithm works, extending FFTrees to more than 2 categories will be a real game changer, as it allows for many additional applications.

**Comment by ndphillips** [comment]
Don't think we'll do this as it would be high effort and I think low reward.
