### ISSUE TITLE
Undocumented requirement or bug: predictive covariates must not be logical type

### ISSUE THREAD

**Issue by jonocarroll** [ndphillips/FFTrees#34]
There appears to be an overlooked condition in `inwords()` in that a predictive covariate of type `"l"` fails to result in an assignment of `sentence.i`, and thus this line errors:

https://github.com/ndphillips/FFTrees/blob/ac259886a85975135cab24a297eed4028d9f37c6/R/inwords.R#L141

I can't tell if this is supposed to be a restriction on the input data (no logical columns) or just a bug, but at first glance it seems like the latter.

Minimal reprexes:

``` r
suppressPackageStartupMessages(library(FFTrees))

## create a perfectly dependent column which is logical
heartdisease2 <- heartdisease
heartdisease2$lgl <- heartdisease2$diagnosis == 1
heart.fft <- FFTrees(formula = diagnosis ~., 
                     data = heartdisease2, 
                     progress = FALSE)
#> Error: object 'sentence.i' not found
```

With an independent logical column, the issue is bypassed

```r
heartdisease2 <- heartdisease
set.seed(1)
heartdisease2$lgl <- sample(c(TRUE, FALSE), nrow(heartdisease), replace = TRUE)
heart.fft <- FFTrees(formula = diagnosis ~., 
                     data = heartdisease2, 
                     progress = FALSE)
heart.fft$inwords
#> [1] "If thal = {rd,fd}, predict True"                   
#> [2] "If cp != {a}, predict False"                       
#> [3] "If ca <= 0, predict False, otherwise, predict True"
```

With a perfectly dependent *integer* column, the issue is bypassed

```r
heartdisease2 <- heartdisease
heartdisease2$lgl <- as.integer(heartdisease2$diagnosis == 1)
heart.fft <- FFTrees(formula = diagnosis ~., 
                     data = heartdisease2, 
                     progress = FALSE)
heart.fft$inwords
#> [1] "If lgl > 0, predict True"                            
#> [2] "If thal != {rd,fd}, predict False"                   
#> [3] "If cp != {a}, predict False, otherwise, predict True"
```

**Comment by ndphillips** [comment]
Thanks for catching this @jonocarroll! This is indeed a bug -- and one where you've pointed me to the exact source :) I'll get to this asap!

**Comment by BenWiseman** [comment]
Has this been fixed yet? It seems to be doing the same thing to me when I use y ~ . as the formula. Looks like an issue with non standard evaluation or something...

**Comment by BenWiseman** [comment]
Randomly getting this error

Error in inwords(tree = tree.max, classes.v = unlist(strsplit(tree.definitions$classes[tree.max],  : 
  object 'sentence.i' not found

**Comment by ndphillips** [comment]
This should have been fixed in version 1.5.0 on master, can you try installing with `devtools::install_github("ndphillips/FFTrees")` and try again? Thanks!

**Comment by BenWiseman** [comment]
I did, at first I thought it was fixed, but nope. Still randomly errors out randomly :/

**Comment by ndphillips** [comment]
@BenWiseman did you try with version 1.5.0? Can you send me your exact code?

**Comment by albertiniufu** [comment]
I'm also getting this error. Version 1.5.5. 
My "context"  follows:

```
> formulacao2
classBol ~ lowHemoglobin + lowSodium + dischargeFromOncology + 
    procedureDuringStay + admissionTypeNonelective + mediumNumberOfAdmissions + 
    highNumberOfAdmissions + lengthOfStay

> str(base)
tibble [47,464 x 14] (S3: tbl_df/tbl/data.frame)
 $ PACIENTEID              : num [1:47464] 62203 96686 303923 385285 519386 ...
 $ ATENDIMENTOID           : num [1:47464] 15184658 15184334 15184301 15184333 15184329 ...
 $ lowHemoglobin           : logi [1:47464] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ dischargeFromOncology   : logi [1:47464] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ lowSodium               : logi [1:47464] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ procedureDuringStay     : logi [1:47464] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ admissionTypeNonelective: logi [1:47464] TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ mediumNumberOfAdmissions: logi [1:47464] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ highNumberOfAdmissions  : logi [1:47464] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ lengthOfStay            : logi [1:47464] TRUE FALSE FALSE TRUE FALSE TRUE ...
 $ class                   : Factor w/ 2 levels "baixoRisco","altoRisco": 1 1 1 1 1 1 1 1 2 1 ...
 $ hospitalScore           : num [1:47464] 3 1 1 3 1 3 4 4 4 1 ...
 $ UFUScore                : num [1:47464] 3 1 1 3 1 3 6 6 6 1 ...
 $ classBol                : logi [1:47464] FALSE FALSE FALSE FALSE FALSE FALSE ...


> tree=FFTrees(formula=formulacao2, data=base)
Setting goal = 'wacc'
Setting goal.chase = 'waccc'
Setting cost.outcomes = list(hi = 0, mi = 1, fa = 1, cr = 0)
Growing FFTs with ifan
[=======================================================================] 100%
Error in fftrees_ffttowords(x = x, digits = 2) : 
  object 'sentence.i' not found

```

**Comment by ndphillips** [comment]
@albertiniufu can you pin it down to a specific feature? That is, can you try running it only including a few specific features in the `formula` argument and see if it's a specific feature that's causing it? 

Alternatively, does it work if you use only the first say 100 rows / cases?

**Comment by ndphillips** [comment]
Thanks for sharing the data with me @albertiniufu , indeed this is a bug that occurs when a cue / feature in the final tree is of class "logical".

I'm in the process of posting a fix, but in the meantime you should be able to bypass the issue by converting all logical columns in your data to numeric (i.e.; 0, 1) or character / factor (i.e.; "TRUE", "FALSE").

Can you try and let me know if it works for you?

**Comment by albertiniufu** [comment]
Thank you for fixing this! 
Using only numeric it works.
