### ISSUE TITLE
Incorrect list key accessed in predict.FFForest

### ISSUE THREAD

**Issue by ncravino** [ndphillips/FFTrees#35]
Hi,

I was checking your work, and found a bug in `predict.FFForest`, that results in the error:
```
Error in matrix(NA, nrow = nrow(data), ncol = n.trees) : 
  non-numeric matrix extent
```
After checking the lastest source file (`predictFFForest_function.R`) I noticed that it tries to access the list key  `tree.sim` to iterate the various trees (lines 17 and 24). However the key with the simulations in the list returned by `FFForest` is named `fft.sim`. 
I tested by renaming the key in the list returned by `FFForest`, and the predict function works without error. 
Perhaps it could be changed in `predict.FFForest`.

Also, great work, these trees provide great explainability that allows to integrate non-technical users with extensive domain knowledge into the modeling decision processes.

**Comment by ndphillips** [comment]
Sorry for the very late reply on this!

Thanks for the note, for now FFForest is deprecated so I won't fix. But if we decide to bring it back I'll refer to this!
