### ISSUE TITLE
Logical DV not considered as so

### ISSUE THREAD

**Issue by MathieuMarauri** [ndphillips/FFTrees#43]
Hello,

Your package and your paper are really interesting, I wanted to give it a try since I saw a presentation at the useR!2017. 

Running the following code I ran into an error. 

```
data("heartdisease")

heartdisease$diagnosis <- as.factor(heartdisease$diagnosis)

set.seed(123)
train_index <- sample(1:nrow(heartdisease), size = nrow(heartdisease) * 4 / 5)
test_index <- setdiff(1:nrow(heartdisease), train_index)
heart_train <- heartdisease[train_index, ]
heart_test <- heartdisease[test_index, ]

heartdisease$diagnosis <- as.logical(heartdisease$diagnosis)

FFTrees(
  formula = diagnosis ~ .,
  data = heart_train,
  data.test = heart_test
)
```

The error is `Error in var(if (is.vector(x) || is.factor(x)) x else as.double(x), na.rm = na.rm) : 
  Calling var(x) on a factor x is defunct.
  Use something like 'all(duplicated(x)[-1L])' to test for a constant vector.` and  I have a message saying that the DV has been coerced to logical which is weird because it is already logical. 

Where am I missing something?

Cheers, 
Mathieu

**Comment by ndphillips** [comment]
hi Mathieu, can you tell me which version of the package you're using?

**Comment by hneth** [comment]
Hi Mathieu and Nathaniel,

I think the error is due to a change in the way the `var(x)` function of R (or rather **stats**) works -- or fails to work -- if `x` is a factor.  Here's a minimal example:

```{r}
v <- 1:10
var(v)  # works

v <- as.factor(v)
var(v)  # yields the error
```

Perhaps something like:

`if (is.factor(v)) var(as.numeric(v))`

would do the trick?

Best,
Hans

**Comment by MathieuMarauri** [comment]
Hello, 

The error is indeed produced by the call to `sd(crit.test)` in the `FFTrees()` function. Replacing this piece of code by `sqrt(var(if (is.vector(crit.test)) crit.test else as.double(crit.test), na.rm = FALSE))` fix the issue.

```
if (is.null(data.test) == FALSE & all(is.finite(crit.test)) & 
        is.finite(sd(crit.test)) & is.null(cue.accuracies.train) == 
        FALSE) {
      if (sd(crit.test) > 0) {
```

is replace by 

```
if (is.null(data.test) == FALSE & all(is.finite(crit.test)) & 
    is.finite(sqrt(var(if (is.vector(crit.test)) crit.test else as.double(crit.test), 
                       na.rm = FALSE))) & is.null(cue.accuracies.train) == 
    FALSE) {
  if (sqrt(var(if (is.vector(crit.test)) crit.test else as.double(crit.test), 
               na.rm = FALSE)) > 0) {
``` 

Another error arises then in the `cuerank()` function. The call to `var(criterion_v)` fails because it is a character (the vector of true/false is considered a character vector). Changing this to factor then numeric should solve the issue. I did not go that far.

Cheers, 
Mathieu

**Comment by hneth** [comment]
Thanks, Mathieu, for locating this issue.  And yes, `sd(x)` yields the same error when `x` is a factor.  But I now wonder whether just converting `x` into numeric data is always a good idea.  Preventing certain numerical operations for categorical variables makes perfect sense, so perhaps a more principled check may be needed when `x` is a factor variable?

Best,
Hans

**Comment by ndphillips** [comment]
@MathieuMarauri Can you tell me which version of the package you are using? I am currently overhauling the package in version 1.5.1 on the `develop` branch and wonder if I've already fixed this.

If you haven't already please try installing this version with:

```
devtools::install_github("ndphillips/FFTrees", ref = "develop")

library(FFTrees)
```

Then see if you get the same error, thanks!

**Comment by MathieuMarauri** [comment]
Hello,

I am using version 1.4.0. I could not load the library after installing from github. I have the following issue. 

```
Error in FUN(X[[i]], ...) : 
  lazy-load database '/Users/.../FFTrees/data/Rdata.rdb' is corrupt
In addition: Warning messages:
1: In FUN(X[[i]], ...) : restarting interrupted promise evaluation
2: In FUN(X[[i]], ...) : internal error -3 in R_decompress1
```
I will try to fix that in a near future but I lack some time for now. 

Cheers,
Mathieu

**Comment by ndphillips** [comment]
Got it, try restarting R, that usually fixes problems like this for me

**Comment by MathieuMarauri** [comment]
The develop branch does solve the issue. Nice work.
