### ISSUE TITLE
algorithms "max" and "zigzag" give hard to understand error messages

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [ndphillips/FFTrees#46]
I can not get FFTrees to use the "max" or "zigzag" algorithms.
Using your example:

```
heart.fft <- FFTrees(formula = diagnosis ~., 
                     data = heart.train,
                     algorithm = "max",
                     data.test = heart.test, 
                     decision.labels = c("Healthy", "Disease"))
```

Gives:
```
Setting goal = 'wacc'
Setting goal.chase = 'waccc'
Setting cost.outcomes = list(hi = 0, mi = 1, fa = 1, cr = 0)
Error in fftrees_define(x, object = object) : 
  I don't know how to define your trees...
```

Only the FFTrees package is loaded.

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

**Comment by ndphillips** [comment]
Yeah I decided to stop supporting "max" and "zigzag". I'll update the error messages to make this clear!

**Comment by Maximilian-Stefan-Ernst** [comment]
Alright, thanks for the quick clarification!

**Comment by ndphillips** [comment]
Added verbose in version 1.5.7 https://github.com/ndphillips/FFTrees/blob/master/R/FFTrees.R#L157-L161
