### ISSUE TITLE
function "fftrees_ranktrees"

### ISSUE THREAD

**Issue by ms1948** [ndphillips/FFTrees#48]
In FFTrees version 1.5.7 when I try to use the function "fftrees_ranktrees", I receive the following error msg: "could not find function "fftrees_ranktrees".

This are the command I have used

library(FFTrees)
library(caret)
library(readxl)
rm(list=ls())
a=read_excel("mydata.xls")
Sit=as.logical(as.numeric(a$Test))
b=data.frame(Sit,a[2:24])
split=0.70
trainIndex <- createDataPartition(b$Sit, p=split, list=FALSE)
data_train <- b[ trainIndex,]
data_test <- b[-trainIndex,]

b.fft <- FFTrees(formula = Sit ~ ., 
                     data = data_train,      
                     data.test = data_test,  
                     main = "Sit (+/-)",  
                     decision.labels = c("Low-Risk", "High-Risk"))

b.fft            
inwords(b.fft)  
summary(b.fft)   

plot(b.fft, data = "test")
plot(b.fft, what = "cues")

fftrees_ranktrees(b.fft , data = "train")

Error in fftrees_ranktrees(b.fft, data = "train") :  could not find function "fftrees_ranktrees"

**Comment by ndphillips** [comment]
Thanks, I think the problem is that `fftrees_ranktrees` is an internal function that is not exported and not intended to be called by users.

However, If you want to use it, then try calling `FFTrees:::fftrees_ranktrees`

Let me know if it works

**Comment by ms1948** [comment]
Ok, thanks it works.

Have a nice day.

--Marco

**Comment by ndphillips** [comment]
Perfect, thanks for getting in touch!
