### ISSUE TITLE
Function Name Concern- Conflict with Fast Fourier Transforms!

### ISSUE THREAD

**Issue by syphax** [ndphillips/FFTrees#5]
I just read the introductory article at https://www.r-bloggers.com/making-fast-good-decisions-with-the-fftrees-r-package/ . I am very interested in the topic and this package.

However, I was rather surprised to see that the function is called **_fft_**; there's a well-established fft function in the stats package for performing Fast Fourier Transforms.

So, before there's too much legacy code out there, might I suggest changing the formula name to, for example, **_fftree_**?

**Comment by ndphillips** [comment]
@syphax Good point. I will update the name (or at least add the alias fftree) in the next update.

In fact, when I initially submitted the package, it was under the name `fft`. The maintainers of CRAN requested that I change the name for the same reason. I should have known to make changes to the function names as well!

**Comment by ndphillips** [comment]
Fixed in `FFTrees 1.1.4`!
