### ISSUE TITLE
FFForest (Fast Frugal Forest) removed?

### ISSUE THREAD

**Issue by degabbersaurus** [ndphillips/FFTrees#52]
Hello,

I want to use the FFTrees package for my research, and I am currently getting the hang of it with the Heart Disease Tutorial. In one of your tutorial videos I saw that the package also supports the use of the FFForest command. **Source** [https://youtu.be/niSdtsqyF7s?t=976](url) Now the FFTrees command works just fine, but the FFForest command seems to be removed or unavailable?

My code is as follows:

```
#Creating a Fast and Frugal Forest
heart.fff <- FFForest(diagnosis ~ .,
              data = heartdisease,
              ntree = 100,
              train.p = .5)

plot(heart.fff)
```

The error that I get when I run the code above is: 
```
Error in FFForest(diagnosis ~ ., data = heartdisease, ntree = 100, train.p = 0.5) : 
  could not find function "FFForest"
```

Also, the FFForest command cannot be found when I use the 'Tab' function in the Rstudio IDE as can be seen with the printscreen.

![Error_FFForest](https://user-images.githubusercontent.com/97548075/168586638-4b30c181-f65d-4e98-8b1f-c537e61aace9.png)

Is the FFForest command removed? And if so, is there a work around? 

Thanks a lot in advance!

**Comment by ndphillips** [comment]
FFForest has indeed been removed from the package
