### ISSUE TITLE
RF and SVM Points in ROC curve have the wrong labels (all are 'C')

### ISSUE THREAD

**Issue by ndphillips** [ndphillips/FFTrees#56]
A user keenly noticed that the points for RF and SVM in the ROC curve created by plot.FFTrees() all have "C" instead of "R" and "S" respectively.

See example from the readme here:

https://raw.githubusercontent.com/ndphillips/FFTrees/master/man/figures/README-example-heart-1.png

The fix should be inhttps://github.com/ndphillips/FFTrees/blob/master/R/plotFFTrees_function.R#L1819-L1979, but looking at it just now I can't see an obvious error.

**Comment by hneth** [comment]
It seems that these labels are manually set to some letter.  

See the bug fix in my upcoming pull request...
