### ISSUE TITLE
Can't plot the non-best tree

### ISSUE THREAD

**Issue by GaryGuan** [ndphillips/FFTrees#6]
In the plot function, the parameter, tree = number, doesn't work.  The best tree was plotted regardless the number.

**Comment by ndphillips** [comment]
@GaryGuan There was a typo in my blog post. The argument should be `which.tree`, not `tree`.

In the next update to the package, I'll officially change the argument name to `tree`. But for now, use `which.tree`

**Comment by GaryGuan** [comment]
Thank you Nathaniel.  It works now.
