### ISSUE TITLE
Creating FFTs from words (using `my.tree`)

### ISSUE THREAD

**Issue by hneth** [ndphillips/FFTrees#69]
When using the `my.tree` argument of `FFTrees()` to create FFTs from verbal descriptions, it is currently only verified that decision labels "False" (i.e., decisions or exits of type 0 / left) appear in `my.tree`.  However, the resulting error message only states that 

- `Some decision.labels are not in my.tree.`

**Suggestion**:  Revise `fftrees_wordstofftrees()`, so that _both_ decision labels/exit types are verified and there is user feedback on which label is missing.

**Comment by hneth** [comment]
The suggestion above is implemented in the latest code addendum to the current PR (#66). 

However, I now realize that both the original and the updated versions are too restrictive after all.  By enforcing that both decision labels (or exit types) are mentioned in the verbal description (of `my.tree`), the benefits of dropping the "otherwise" part of the final conditional statement are lost --- at least for _rake_ trees, which really only need to specify _one_ decision label or exit type (prior to the "otherwise" part). 

**Suggestion**:  Turn the current `stop()`s into user `warning()`s (that provide feedback on which decision labels are missing), but then continue and try growing the tree that was described.

**Comment by ndphillips** [comment]
Big +1!

**Comment by hneth** [comment]
**Thanks!**  I'll look into a more comprehensive validity checking option of verbal user inputs in the future, but will close the present issue now.
