### ISSUE TITLE
Combining data documentation files?

### ISSUE THREAD

**Issue by hneth** [ndphillips/FFTrees#74]
It's very valuable that **FFTrees** comes with so many interesting example datasets.  

However, their documentation as separate `.R` files currently clutters the code directory (which is otherwise organized very systematically) and does not seem to serve any important purpose.  Hence, I propose the following

**Suggestion**:

- Combine all data documentations in a single code file `(e.g. `FFT_data_doc.R`). 

Please let me know if there are any ideas or objections to this — otherwise I'd just try it out...

**Comment by ndphillips** [comment]
Sure works for me!

**Comment by hneth** [comment]
**Thanks** for the quick reply — and done (in PR #73 ).
